export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_ADVERSE_EFFECTS_SUCCESS = 'LOAD_ADVERSE_EFFECTS_SUCCESS';
export const CREATE_ADVERSE_EFFECT_SUCCESS = 'CREATE_ADVERSE_EFFECTS_SUCCESS';
export const UPDATE_ADVERSE_EFFECT_SUCCESS = 'UPDATE_ADVERSE_EFFECTS_SUCCESS';
export const DELETE_ADVERSE_EFFECT_SUCCESS = 'DELETE_ADVERSE_EFFECTS_SUCCESS';